name: Geometry Minecraft CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Scratch-CreadorCraft-Maker
        uses: Creadores-Program/Scratch-to-CreadorCraft-Maker-GHA@v1.1.0
        with:
          path: "./GeometryMC/src" # Destinity CreadorCraft Game (this not genere manifest.json)
          # id: "id" Id by game Scratch
          # url: "url" Url by game Scratch
          pathGame: "./GeometryMC/GeometryMinecraft1.sb3" # Only uses 1 of the above
      # Pack..
      - name: CreadorCraft-Maker
        uses: Creadores-Program/CreadorCraft-Maker-GHA@v1.1.0
        with:
          path: "./GeometryMC/src"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Geometry Minecraft 1
          path: gameBuildCCM/Geometry Minecraft 1.0.0.creadorcraftgame.zip
